#!/usr/bin/env bash

set -e

timeout=3

if [[ "${APP_ENVIRONMENT}" == "production" ]]; then
    start_type="docker"
else
    start_type="development"
fi

echo "Starting App service..." ${APP_ENVIRONMENT};
yarn start:$start_type